### ISSUE TITLE
pytest -v test.py throwing an error

### ISSUE THREAD

**Issue by yevyev** [kyclark/tiny_python_projects#27]
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.18, pytest-4.6.9, py-1.8.1, pluggy-0.13.0 -- /usr/bin/python2
cachedir: .pytest_cache
rootdir: /home/yev/Documents/PyProjects/tinypythonprojects/tiny_python_projects/01_hello
collected 0 items / 1 errors                                                                                                                                               

================================================================================== ERRORS ==================================================================================
_________________________________________________________________________ ERROR collecting test.py _________________________________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/home/yev/Documents/PyProjects/tinypythonprojects/tiny_python_projects/01_hello/test.py", line 21
E       out = getoutput(f'python3 {prg}')
E                                      ^
E   SyntaxError: invalid syntax
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================= 1 error in 0.09 seconds ==========================================================================

I'm unsure why it's using python2, and how to fix this.

I'm using Ubuntu 20.04.

**Comment by nbehrnd** [comment]
yevyev ***@***.***> wrote:

> I'm unsure why it's using python2, and how to fix this.
> 
> I'm using Ubuntu 20.04.

True, the fresh default installation of Ubuntu 20.04 LTS substituted
Python 2 by Python 3.  However, if you transition e.g., from an
already existing and running Xubuntu 16.04 LTS to 20.04 LTS by system
upgrade, an already existing Python2 stays in the system.

Possible solutions (not exhaustive):
+ With about half a year ahead of Ubuntu's point release 22.04.1
  which then will trigger synaptic to suggest again an upgrade of
  the distribution 20.04 -> 22.04, an adjustment of the path variable
  may offer help here.  One of the first entries found on
  stackoverflow about this topic is

   ```bash
   mkdir ~/bin
   PATH=~/bin:$PATH
   ln -s /usr/bin/python2 ~/bin/python
   ```
   (source: [1])


+ Or, an adjustment with `sudo update-alternatives` as documented
  e.g., on stackoverlow.[2]

Obviously, both may require an adjustment of the shebang line in
scripts written in Python2.  With `2to3`,[3] their transition to
Python3 may be more consistent, than by hands-on only; because it is
not only about print where Python2 and Python3 differ from each other.


[1]
https://stackoverflow.com/questions/7237415/python-2-instead-of-python-3-as-the-temporary-default-python
[2]
https://stackoverflow.com/questions/60967660/how-to-remove-python2-in-ubuntu
[3]
https://packages.ubuntu.com/search?keywords=2to3&searchon=names&suite=all&section=all
